version: '3.1'

secrets:
  postgres_password:
    file: "./secrets/postgres_password.secret"

services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=postgres:5432
      - RUN_MODE=prod
    restart: always

    networks:
      - web
      - gitea

    volumes:
      - ./data/gitea:/data

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`git.cyril-tavian.fr`)"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.routers.gitea.tls.certresolver=letsencrypt"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.tcp.routers.gitea-ssh.rule=Host(`git.cyril-tavian.fr`)"
      - "traefik.tcp.routers.gitea-ssh.entrypoints=ssh"
      - "traefik.tcp.services.gitea-ssh.loadbalancer.server.port=22"

  postgres:
    image: postgres:9.6
    restart: always
    secrets: 
      - postgres_password
    environment: 
      - POSTGRES_USER=gitea
      - POSTGRES_DB=gitea
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    networks: 
      - gitea
    volumes: 
     - ./data/postgres:/var/lib/postgresql/data

networks:
  web:
    external: true
  gitea: 
    external: false
