log:
  level: DEBUG

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: "web"

certificatesResolvers:
  caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
  letsencrypt:
    acme:
      email: "c.tavian@outlook.fr"
      storage: "/acme.json"
      dnsChallenge:
        provider: ovh
        delayBeforeCheck: 10
